name: kotonosyky
description: A website for kotonosyky.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.3
  json_annotation: ^4.8.1
  cloud_firestore_odm: ^1.0.0-dev.63
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^10.0.0
  url_launcher: ^6.1.11
  markdown: ^7.1.1
  flutter_markdown: ^0.6.15
  font_awesome_flutter: ^10.4.0
  firebase_analytics: ^10.7.0
  firebase_analytics_web: ^0.5.5+7
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.1.1
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/